name: Build site

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "15 9 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pandas numpy pyyaml requests

      - name: Run pipeline (writes data/*.csv)
        env:
          CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}
        run: python run_all.py

      - name: Prepare _site (publish ONLY data/)
        run: |
          rm -rf _site
          mkdir -p _site/data
          cp -r data/* _site/data/ || true

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site
