name: Build & Deploy Data

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "15 9 * * *"   # daily 09:15 UTC; adjust if you like
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipeline (creates data/*.csv)
        env:
          CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}
        run: |
          python run_all.py

      - name: Prepare site content (only publish data/)
        run: |
          rm -rf _site
          mkdir -p _site/data
          cp -r data/* _site/data/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
