name: CFB Auto Update

on:
  schedule:
    - cron: "15 9 * * *"   # daily 09:15 UTC (change as you like)
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipeline (produces data/*.csv)
        env:
          CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}
        run: |
          python run_all.py

      # Save data/ as an artifact for the Pages job
      - name: Upload site artifact (data only)
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the whole repo but only keep data/ when deploying Pages (see deploy job)
          path: .
